sonar.organization=divyasrikadirisani035-bit
sonar.projectKey=divyasrikadirisani035-bit_ultimate-devops-project-demo-with-infra-divya
sonar.projectName=payment-service
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**,dist/**,build/**,.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info