apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 85.1.2
    helm:
      releaseName: monitoring
      values: |
        fullnameOverride: monitoring

        grafana:
          enabled: true
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

        prometheus:
          prometheusSpec:
            retention: 2h
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi

        alertmanager:
          enabled: false

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
